/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_sinoauto_hq_oos_propeller_preprocessing_VideoPreProcessing */

#ifndef _Included_com_sinoautodiagnoseos_propeller_preprocessing_VideoPreProcessing
#define _Included_com_sinoautodiagnoseos_propeller_preprocessing_VideoPreProcessing
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_sinoauto_hq_oos_propeller_preprocessing_VideoPreProcessing
 * Method:    enablePreProcessing
 * Signature: (Z)V
 */
JNIEXPORT void JNICALL Java_com_sinoautodiagnoseos_propeller_preprocessing_VideoPreProcessing_enablePreProcessing
  (JNIEnv *, jobject, jboolean);

#ifdef __cplusplus
}
#endif
#endif
